apiVersion: v1
kind: Service
metadata:
  name: {{ include "asi.ergo.fullname" . }}
  labels:
    {{- include "asi.labels" . | nindent 4 }}
    app.kubernetes.io/component: ergo
spec:
  type: {{ .Values.ergo.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ergo
  ports:
    - name: irc
      port: {{ .Values.ergo.plainPort }}
      targetPort: irc
    - name: ircs
      port: {{ .Values.ergo.tlsPort }}
      targetPort: ircs
